import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'My Next Board Sample',
  description: 'Generated by jswon'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>
          <Link href="/">Home</Link>
        </h1>
        {children}
        <ol>
          <li>
            <Link href="/list">List</Link>
          </li>
          <li>
            <Link href="/post">Post</Link>
          </li>
        </ol>
      </body>
    </html>
  );
}
